AddEventHandler('onResourceStart', function(resourceName)
    if resourceName == GetCurrentResourceName() then
        if resourceName ~= "drowsy-tp" then
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            print('(^6https://spoody.dev/) ^0Unauthorized Use.')
            Citizen.Wait(1500)
            os.exit()
        end
    end
end)